CREATE TABLE FAKULTAS (
  ID_FAKULTAS SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FAKULTAS VARCHAR(45) NULL,
  PRIMARY KEY(ID_FAKULTAS)
);

CREATE TABLE JURUSAN (
  ID_JURUSAN SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FAKULTAS_ID_FAKULTAS SMALLINT UNSIGNED NOT NULL,
  JURUSAN VARCHAR(45) NULL,
  PRIMARY KEY(ID_JURUSAN),
  INDEX JURUSAN_FKIndex1(FAKULTAS_ID_FAKULTAS)
);

CREATE TABLE MAHASISWA (
  NIM VARCHAR(15) NOT NULL AUTO_INCREMENT,
  SELEKSI_MASUK_ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL,
  PROGRAM_STUDI_ID_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL,
  NAMA VARCHAR(45) NULL,
  ANGKATAN SMALLINT UNSIGNED NULL,
  TGL_LAHIR DATE NULL,
  KOTA_LAHIR VARCHAR(60) NULL,
  JENIS_KELAMIN CHAR(1) NULL,
  PRIMARY KEY(NIM),
  INDEX MAHASISWA_FKIndex1(PROGRAM_STUDI_ID_PROGRAM_STUDI),
  INDEX MAHASISWA_FKIndex2(SELEKSI_MASUK_ID_SELEKSI_MASUK)
);

CREATE TABLE PROGRAM_STUDI (
  ID_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  STRATA_ID_STRATA SMALLINT UNSIGNED NOT NULL,
  JURUSAN_ID_JURUSAN SMALLINT UNSIGNED NOT NULL,
  PROGRAM_STUDI VARCHAR(60) NULL,
  PRIMARY KEY(ID_PROGRAM_STUDI),
  INDEX PROGRAM_STUDI_FKIndex1(JURUSAN_ID_JURUSAN),
  INDEX PROGRAM_STUDI_FKIndex2(STRATA_ID_STRATA)
);

CREATE TABLE SELEKSI_MASUK (
  ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  SINGKAT VARCHAR(12) NULL,
  SELEKSI_MASUK VARCHAR(45) NULL,
  PRIMARY KEY(ID_SELEKSI_MASUK)
);

CREATE TABLE STRATA (
  ID_STRATA SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  SINGKAT VARCHAR(10) NULL,
  STRATA VARCHAR(45) NULL,
  PRIMARY KEY(ID_STRATA)
);