CREATE TABLE MOVIE (
    KODE_DVD VARCHAR(10),
    JUDUL VARCHAR(60),
    HARGA_SEWA DOUBLE,
    DENDA DOUBLE,
    TAHUN_RILIS SMALLINT
);

CREATE TABLE TRANSAKSI (
    KODE_DVD VARCHAR(10)(FK),
    KODE_PELANGGAN VARCHAR(10)(FK),
    TANGGAL_SEWA DATE,
    TANGGAL_WAJIB_KEMBALI DATE,
    TANGGAL_REALISASI_KEMBALI DATE
);

CREATE TABLE GENRE_MOVIE (
    ID_GENRE SMALLINT(FK),
    KODE_DVD VARCHAR(10)(FK)
);

CREATE TABLE PELANGGAN (
    KODE_PELANGGAN VARCHAR(10),
    ID_KELURAHAN SMALLINT(FK)
    NAMA VARCHAR(45)
    ALAMAT VARCHAR(60)
    JENIS_KELAMIN CHAR(1) CHECK (JENIS_KELAMIN IN ('P', 'L'))
);

CREATE TABLE KONTAK_PELANGGAN (
    NO_HP VARCHAR(25),
    KODE_PELANGGAN VARCHAR(10)(FK),
    KONTAK_PELANGGAN_UNIK1,
    NO_HP
);

CREATE TABLE KECAMATAN (
    ID_KECAMATAN SMALLINT,
    KECAMATAN VARCHAR(45)
);

CREATE TABLE KELURAHAN (
    ID_KELURAHAN SMALLINT
    ID_KECAMATAN SMALLINT(FK),
    KELURAHAN VARCHAR(45)
);

CREATE TABLE GENRE (
    ID_GENRE SMALLINT,
    GENRE VARCHAR(45)
);